services:
  landing-page:
    build:
      context: ./LandingPage
      dockerfile: Dockerfile
    container_name: landing_page_app
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ./LandingPage:/usr/share/nginx/html:ro
