name: Auto Deploy to Proxmox

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Proxmox
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Restart Docker Container
        run: |
          docker compose up -d --build
          docker image prune -f
